behaviors:
  DifficultyAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128  # Zwiększona stabilność
      buffer_size: 4096  # Większa pojemność dla PPO
      learning_rate: 2.5e-4  # Nieco niższy LR dla stabilności
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8  # Większa liczba epok dla lepszego wykorzystania danych
    network_settings:
      normalize: true
      hidden_units: 256  # Więcej neuronów dla lepszej reprezentacji
      num_layers: 3  # Głębsza sieć
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:  # Dodanie nagrody za eksplorację
        gamma: 0.99
        strength: 0.01
    max_steps: 2e6  # Więcej kroków do pełnego treningu
    time_horizon: 128  # Większy horyzont czasowy dla lepszego kontekstu
    summary_freq: 5000
    keep_checkpoints: 5
