behaviors:
  RLModel:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128  # Zwiększone dla stabilności
      buffer_size: 4096  # Większy bufor dla PPO
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256  # Zwiększona liczba neuronów dla lepszej precyzji
      num_layers: 3  # Głębsza sieć dla lepszego dopasowania
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 750000  # Więcej iteracji dla stabilniejszego treningu
    time_horizon: 128  # Zwiększone dla bardziej stabilnego uczenia
    summary_freq: 20000  # Rzadsze logowanie dla większej wydajności