//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/PLAYER TWO/ARPG Project/Examples/Inputs/Entity Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @EntityControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @EntityControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Entity Controls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""0608742c-0a98-4be9-a40d-4e24c8b6c89b"",
            ""actions"": [
                {
                    ""name"": ""Set Destination"",
                    ""type"": ""Value"",
                    ""id"": ""277b648d-a0a4-4705-bfdb-3b57ee2687c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack Mode"",
                    ""type"": ""Button"",
                    ""id"": ""6af5f1d5-c0c7-49f7-a096-1c5916e1b866"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill"",
                    ""type"": ""Button"",
                    ""id"": ""0d3ffb39-1f5d-48d1-bdd0-f29242799e88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Consume Item 0"",
                    ""type"": ""Button"",
                    ""id"": ""68770144-ecea-4afc-bec1-17bef27ce90a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Consume Item 1"",
                    ""type"": ""Button"",
                    ""id"": ""a693e04c-e66b-4fe4-b14d-0226d7d865c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Consume Item 2"",
                    ""type"": ""Button"",
                    ""id"": ""4451636d-6d35-45c6-b64a-d111f268cd28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Consume Item 3"",
                    ""type"": ""Button"",
                    ""id"": ""c5fb7df3-4ee7-4601-bb89-dbfe8b463b89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 0"",
                    ""type"": ""Button"",
                    ""id"": ""da4da96c-b9e7-4e70-ac67-46adb55572f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 1"",
                    ""type"": ""Button"",
                    ""id"": ""e99847be-a207-4e42-a2cb-f638bed65831"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 2"",
                    ""type"": ""Button"",
                    ""id"": ""19cbb8a6-2308-4bee-a21d-ec5ed3b4b4ee"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 3"",
                    ""type"": ""Button"",
                    ""id"": ""b35a25e7-235b-4cb0-a281-b527f9ef13bf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 4"",
                    ""type"": ""Button"",
                    ""id"": ""ecb2ee36-2e2c-4ce3-926d-c13e66a73ddd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 5"",
                    ""type"": ""Button"",
                    ""id"": ""a2a57ee3-8779-4c3f-8836-43cf28f13707"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 6"",
                    ""type"": ""Button"",
                    ""id"": ""4c76f3c3-3e63-4edf-90af-8f796aad61c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Skill 7"",
                    ""type"": ""Button"",
                    ""id"": ""b40fd131-5563-428f-82bb-eb2e84ae1bb9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Directional Movement"",
                    ""type"": ""Value"",
                    ""id"": ""65ba34b8-387e-480d-8745-7c1bae6beacd"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""be5fbdea-ad29-4c41-83a6-5bdad2ccebf5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""d9e595d1-5e48-40dd-b18a-9a8fe754317b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""58ff0198-fecf-44bc-935e-424861217765"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Set Destination"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98db22ba-c568-4a9a-92c5-6dce794019e8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ecc6892-d5d7-4a23-8151-40e4919bdf31"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70f2ea7e-f55f-438e-90bc-be1b531e0456"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2de52107-4798-48d1-9991-89c939d79af8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a246c08-4682-4049-87f1-cd40ed31a60a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dc73e56-77f9-4d0a-af73-c1aeae2754f1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48cee6a3-2dd3-4ed6-8e95-7ceb7afd6044"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11fc45bf-44ca-4453-b6e5-7f7378f226c6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9850345-8fd6-480d-ab10-c332069fd200"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18599e42-3165-4da0-bba0-a39e373a0493"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""181046b9-0d07-445a-aa05-8aab7c1d1754"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Skill 7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bcf3ac8-1249-4db6-b256-0f73a92e8850"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consume Item 0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""090ada7b-9a4e-4c65-a7a1-84d71cedda19"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consume Item 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64d9d495-d0e0-4ade-9190-b3c6c7189198"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consume Item 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a9f7666-03e0-420f-b305-6ac941d34d82"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consume Item 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""213b4dc9-9329-416e-a8e4-6cf2293683b1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directional Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91b571fc-ea98-4b3c-8549-871984d7c9f6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7ed6caf-c23d-4788-bb15-dca5b049f3ea"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_SetDestination = m_Gameplay.FindAction("Set Destination", throwIfNotFound: true);
        m_Gameplay_AttackMode = m_Gameplay.FindAction("Attack Mode", throwIfNotFound: true);
        m_Gameplay_Skill = m_Gameplay.FindAction("Skill", throwIfNotFound: true);
        m_Gameplay_ConsumeItem0 = m_Gameplay.FindAction("Consume Item 0", throwIfNotFound: true);
        m_Gameplay_ConsumeItem1 = m_Gameplay.FindAction("Consume Item 1", throwIfNotFound: true);
        m_Gameplay_ConsumeItem2 = m_Gameplay.FindAction("Consume Item 2", throwIfNotFound: true);
        m_Gameplay_ConsumeItem3 = m_Gameplay.FindAction("Consume Item 3", throwIfNotFound: true);
        m_Gameplay_SelectSkill0 = m_Gameplay.FindAction("Select Skill 0", throwIfNotFound: true);
        m_Gameplay_SelectSkill1 = m_Gameplay.FindAction("Select Skill 1", throwIfNotFound: true);
        m_Gameplay_SelectSkill2 = m_Gameplay.FindAction("Select Skill 2", throwIfNotFound: true);
        m_Gameplay_SelectSkill3 = m_Gameplay.FindAction("Select Skill 3", throwIfNotFound: true);
        m_Gameplay_SelectSkill4 = m_Gameplay.FindAction("Select Skill 4", throwIfNotFound: true);
        m_Gameplay_SelectSkill5 = m_Gameplay.FindAction("Select Skill 5", throwIfNotFound: true);
        m_Gameplay_SelectSkill6 = m_Gameplay.FindAction("Select Skill 6", throwIfNotFound: true);
        m_Gameplay_SelectSkill7 = m_Gameplay.FindAction("Select Skill 7", throwIfNotFound: true);
        m_Gameplay_DirectionalMovement = m_Gameplay.FindAction("Directional Movement", throwIfNotFound: true);
        m_Gameplay_Attack = m_Gameplay.FindAction("Attack", throwIfNotFound: true);
        m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
    }

    ~@EntityControls()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, EntityControls.Gameplay.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_SetDestination;
    private readonly InputAction m_Gameplay_AttackMode;
    private readonly InputAction m_Gameplay_Skill;
    private readonly InputAction m_Gameplay_ConsumeItem0;
    private readonly InputAction m_Gameplay_ConsumeItem1;
    private readonly InputAction m_Gameplay_ConsumeItem2;
    private readonly InputAction m_Gameplay_ConsumeItem3;
    private readonly InputAction m_Gameplay_SelectSkill0;
    private readonly InputAction m_Gameplay_SelectSkill1;
    private readonly InputAction m_Gameplay_SelectSkill2;
    private readonly InputAction m_Gameplay_SelectSkill3;
    private readonly InputAction m_Gameplay_SelectSkill4;
    private readonly InputAction m_Gameplay_SelectSkill5;
    private readonly InputAction m_Gameplay_SelectSkill6;
    private readonly InputAction m_Gameplay_SelectSkill7;
    private readonly InputAction m_Gameplay_DirectionalMovement;
    private readonly InputAction m_Gameplay_Attack;
    private readonly InputAction m_Gameplay_Interact;
    public struct GameplayActions
    {
        private @EntityControls m_Wrapper;
        public GameplayActions(@EntityControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SetDestination => m_Wrapper.m_Gameplay_SetDestination;
        public InputAction @AttackMode => m_Wrapper.m_Gameplay_AttackMode;
        public InputAction @Skill => m_Wrapper.m_Gameplay_Skill;
        public InputAction @ConsumeItem0 => m_Wrapper.m_Gameplay_ConsumeItem0;
        public InputAction @ConsumeItem1 => m_Wrapper.m_Gameplay_ConsumeItem1;
        public InputAction @ConsumeItem2 => m_Wrapper.m_Gameplay_ConsumeItem2;
        public InputAction @ConsumeItem3 => m_Wrapper.m_Gameplay_ConsumeItem3;
        public InputAction @SelectSkill0 => m_Wrapper.m_Gameplay_SelectSkill0;
        public InputAction @SelectSkill1 => m_Wrapper.m_Gameplay_SelectSkill1;
        public InputAction @SelectSkill2 => m_Wrapper.m_Gameplay_SelectSkill2;
        public InputAction @SelectSkill3 => m_Wrapper.m_Gameplay_SelectSkill3;
        public InputAction @SelectSkill4 => m_Wrapper.m_Gameplay_SelectSkill4;
        public InputAction @SelectSkill5 => m_Wrapper.m_Gameplay_SelectSkill5;
        public InputAction @SelectSkill6 => m_Wrapper.m_Gameplay_SelectSkill6;
        public InputAction @SelectSkill7 => m_Wrapper.m_Gameplay_SelectSkill7;
        public InputAction @DirectionalMovement => m_Wrapper.m_Gameplay_DirectionalMovement;
        public InputAction @Attack => m_Wrapper.m_Gameplay_Attack;
        public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @SetDestination.started += instance.OnSetDestination;
            @SetDestination.performed += instance.OnSetDestination;
            @SetDestination.canceled += instance.OnSetDestination;
            @AttackMode.started += instance.OnAttackMode;
            @AttackMode.performed += instance.OnAttackMode;
            @AttackMode.canceled += instance.OnAttackMode;
            @Skill.started += instance.OnSkill;
            @Skill.performed += instance.OnSkill;
            @Skill.canceled += instance.OnSkill;
            @ConsumeItem0.started += instance.OnConsumeItem0;
            @ConsumeItem0.performed += instance.OnConsumeItem0;
            @ConsumeItem0.canceled += instance.OnConsumeItem0;
            @ConsumeItem1.started += instance.OnConsumeItem1;
            @ConsumeItem1.performed += instance.OnConsumeItem1;
            @ConsumeItem1.canceled += instance.OnConsumeItem1;
            @ConsumeItem2.started += instance.OnConsumeItem2;
            @ConsumeItem2.performed += instance.OnConsumeItem2;
            @ConsumeItem2.canceled += instance.OnConsumeItem2;
            @ConsumeItem3.started += instance.OnConsumeItem3;
            @ConsumeItem3.performed += instance.OnConsumeItem3;
            @ConsumeItem3.canceled += instance.OnConsumeItem3;
            @SelectSkill0.started += instance.OnSelectSkill0;
            @SelectSkill0.performed += instance.OnSelectSkill0;
            @SelectSkill0.canceled += instance.OnSelectSkill0;
            @SelectSkill1.started += instance.OnSelectSkill1;
            @SelectSkill1.performed += instance.OnSelectSkill1;
            @SelectSkill1.canceled += instance.OnSelectSkill1;
            @SelectSkill2.started += instance.OnSelectSkill2;
            @SelectSkill2.performed += instance.OnSelectSkill2;
            @SelectSkill2.canceled += instance.OnSelectSkill2;
            @SelectSkill3.started += instance.OnSelectSkill3;
            @SelectSkill3.performed += instance.OnSelectSkill3;
            @SelectSkill3.canceled += instance.OnSelectSkill3;
            @SelectSkill4.started += instance.OnSelectSkill4;
            @SelectSkill4.performed += instance.OnSelectSkill4;
            @SelectSkill4.canceled += instance.OnSelectSkill4;
            @SelectSkill5.started += instance.OnSelectSkill5;
            @SelectSkill5.performed += instance.OnSelectSkill5;
            @SelectSkill5.canceled += instance.OnSelectSkill5;
            @SelectSkill6.started += instance.OnSelectSkill6;
            @SelectSkill6.performed += instance.OnSelectSkill6;
            @SelectSkill6.canceled += instance.OnSelectSkill6;
            @SelectSkill7.started += instance.OnSelectSkill7;
            @SelectSkill7.performed += instance.OnSelectSkill7;
            @SelectSkill7.canceled += instance.OnSelectSkill7;
            @DirectionalMovement.started += instance.OnDirectionalMovement;
            @DirectionalMovement.performed += instance.OnDirectionalMovement;
            @DirectionalMovement.canceled += instance.OnDirectionalMovement;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @SetDestination.started -= instance.OnSetDestination;
            @SetDestination.performed -= instance.OnSetDestination;
            @SetDestination.canceled -= instance.OnSetDestination;
            @AttackMode.started -= instance.OnAttackMode;
            @AttackMode.performed -= instance.OnAttackMode;
            @AttackMode.canceled -= instance.OnAttackMode;
            @Skill.started -= instance.OnSkill;
            @Skill.performed -= instance.OnSkill;
            @Skill.canceled -= instance.OnSkill;
            @ConsumeItem0.started -= instance.OnConsumeItem0;
            @ConsumeItem0.performed -= instance.OnConsumeItem0;
            @ConsumeItem0.canceled -= instance.OnConsumeItem0;
            @ConsumeItem1.started -= instance.OnConsumeItem1;
            @ConsumeItem1.performed -= instance.OnConsumeItem1;
            @ConsumeItem1.canceled -= instance.OnConsumeItem1;
            @ConsumeItem2.started -= instance.OnConsumeItem2;
            @ConsumeItem2.performed -= instance.OnConsumeItem2;
            @ConsumeItem2.canceled -= instance.OnConsumeItem2;
            @ConsumeItem3.started -= instance.OnConsumeItem3;
            @ConsumeItem3.performed -= instance.OnConsumeItem3;
            @ConsumeItem3.canceled -= instance.OnConsumeItem3;
            @SelectSkill0.started -= instance.OnSelectSkill0;
            @SelectSkill0.performed -= instance.OnSelectSkill0;
            @SelectSkill0.canceled -= instance.OnSelectSkill0;
            @SelectSkill1.started -= instance.OnSelectSkill1;
            @SelectSkill1.performed -= instance.OnSelectSkill1;
            @SelectSkill1.canceled -= instance.OnSelectSkill1;
            @SelectSkill2.started -= instance.OnSelectSkill2;
            @SelectSkill2.performed -= instance.OnSelectSkill2;
            @SelectSkill2.canceled -= instance.OnSelectSkill2;
            @SelectSkill3.started -= instance.OnSelectSkill3;
            @SelectSkill3.performed -= instance.OnSelectSkill3;
            @SelectSkill3.canceled -= instance.OnSelectSkill3;
            @SelectSkill4.started -= instance.OnSelectSkill4;
            @SelectSkill4.performed -= instance.OnSelectSkill4;
            @SelectSkill4.canceled -= instance.OnSelectSkill4;
            @SelectSkill5.started -= instance.OnSelectSkill5;
            @SelectSkill5.performed -= instance.OnSelectSkill5;
            @SelectSkill5.canceled -= instance.OnSelectSkill5;
            @SelectSkill6.started -= instance.OnSelectSkill6;
            @SelectSkill6.performed -= instance.OnSelectSkill6;
            @SelectSkill6.canceled -= instance.OnSelectSkill6;
            @SelectSkill7.started -= instance.OnSelectSkill7;
            @SelectSkill7.performed -= instance.OnSelectSkill7;
            @SelectSkill7.canceled -= instance.OnSelectSkill7;
            @DirectionalMovement.started -= instance.OnDirectionalMovement;
            @DirectionalMovement.performed -= instance.OnDirectionalMovement;
            @DirectionalMovement.canceled -= instance.OnDirectionalMovement;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnSetDestination(InputAction.CallbackContext context);
        void OnAttackMode(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnConsumeItem0(InputAction.CallbackContext context);
        void OnConsumeItem1(InputAction.CallbackContext context);
        void OnConsumeItem2(InputAction.CallbackContext context);
        void OnConsumeItem3(InputAction.CallbackContext context);
        void OnSelectSkill0(InputAction.CallbackContext context);
        void OnSelectSkill1(InputAction.CallbackContext context);
        void OnSelectSkill2(InputAction.CallbackContext context);
        void OnSelectSkill3(InputAction.CallbackContext context);
        void OnSelectSkill4(InputAction.CallbackContext context);
        void OnSelectSkill5(InputAction.CallbackContext context);
        void OnSelectSkill6(InputAction.CallbackContext context);
        void OnSelectSkill7(InputAction.CallbackContext context);
        void OnDirectionalMovement(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
